services:
  mysql:
    image: mysql:8.4
    container_name: hospital-mysql
    environment:
      MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_PASSWORD: 2030
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p2030"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: hospital-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2030
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql_data:
